### ISSUE TITLE
The results of multiple executions of the decryption function are inconsistent

### ISSUE THREAD

**Issue by Comdex** [o1-labs/snarkyjs#442]
The correct private key and ciphertext were used for decryption in snarkyjs, and the results of repeated execution were inconsistent. Sometimes the decryption was successful, and sometimes an error was thrown, as shown in the screenshot below:

![error](https://user-images.githubusercontent.com/3725514/192476659-c2b39189-938b-4bfa-9c06-112a262f7109.PNG)

snarkyjs version: 0.6.0
sample code to reproduce the problem(execute the same code multiple times): 
```typescript
import { isReady, PrivateKey, Encoding, Encryption, PublicKey } from 'snarkyjs';

await isReady;

let privateKey = PrivateKey.random();
let publicKey = privateKey.toPublicKey();
console.log('publicKey: ', publicKey.toBase58());

let messageFields = publicKey.toFields();
let cipherText = Encryption.encrypt(messageFields, publicKey);
console.log('ciphertext fs length: ', cipherText.cipherText.length);

let fs = Encryption.decrypt(cipherText, privateKey);
console.log('fs length: ', fs.length);

let pub = PublicKey.ofFields(fs);
console.log('origin publickey: ', pub.toBase58());
```

**Comment by Comdex** [comment]
@Trivo25  Running the above sample code under ubuntu and win10 will still occasionally report errors.

snarkyjs version: 0.7.3
node version: v16.13.0

![err](https://user-images.githubusercontent.com/3725514/211456079-ca2bcf4a-f949-407e-a6fb-d671da5c0da3.PNG)

**Comment by Trivo25** [comment]
Thanks! I will look into it again

**Comment by nicc** [comment]
New brief: @Trivo25 to hand over to crypto team with thorough explanation.

**Comment by nicc** [comment]
Write regression test when fixing

**Comment by Trivo25** [comment]
The bug seems to be caused if `message` includes at least one `Field(0)` at any position. The example seemingly randomly fails because we try to encrypt the serialized public key, which group points can sometimes be odd `Field(0)` or even `Field(1)`. If the `message` includes a `Field(0)`,[ it fails to calculate the correct `authenticationTag`](https://github.com/o1-labs/snarkyjs/blob/main/src/lib/encryption.ts#L66) when decrypting the cipher text.

**Comment by coldstar1993** [comment]
hi there, how about this issue?? This is key for our current project -- Anomix,  expecting further updates. Appreciate.

**Comment by joseandro** [comment]
Further investigation from the Crypto team is planned for this sprint.

**Comment by fabrizio-m** [comment]
It was an error in the snarky sponge implementation. I already merged a fix there https://github.com/o1-labs/snarky/pull/825, it was an internal change, just updating the dependency should be enough here.

The problem is with `Poseidon`, for example:
```javascript
await isReady;

let sponge = new Poseidon.Sponge();
let f = Field.random();
let x = sponge.squeeze()
console.log(x.toString());
sponge.absorb(f);
console.log(x.toString());
```
Will print two different values even when we didn't do anything to `x`, the problem was that calls to `squeeze` returned a reference to the sponge state instead of a copy or it, later calls to `absorbe` could mutate the state and thus your element.
In this case it resulted in the ciphertext being altered before being returned by `encrypt` in cases where the message contained `0`s and then the `decrypt` function properly rejecting the altered ciphertext.
Keep it in mind for any cases that use `Poseidon` in some way, or at least calls `absorbe` after `squeeze`, even if there are no `0`s involved.

**Comment by Isaac-DeFrain** [comment]
Should this fix be reflected in this repo now? I was attempting to add a small regression test on top of commit `63521d6fbdcda2771ee94f5c3f2a801d5e3b5d9b`, e.g.

```typescript
// src/lib/encrypt-decrypt.unit-test.ts

import { isReady, Encryption, PrivateKey, PublicKey, shutdown } from 'snarkyjs';

await isReady;

for (let n = 0; n < 100; n++) {
    let sk = PrivateKey.random();
    let pk = sk.toPublicKey();
    let ct = Encryption.encrypt(pk.toFields(), pk);
    let fs = Encryption.decrypt(ct, sk);
    let pub = PublicKey.fromFields(fs);
    pk.assertEquals(pub);
}

shutdown();
```

but this is still throwing an error.

**Comment by mitschabaude** [comment]
thanks for bringing that up @Isaac-DeFrain! it's not reflected in snarkyjs yet (the fix is in `snarky/master`). Our usual slow processes (`snarky` getting updated in `Mina/develop`, `Mina/develop` getting merged into `Mina/rampup` which is the Mina branch that snarkyjs uses) would ensure that the fix eventually ends up in snarkyjs, but we could also make that happen in a more proactive way, wdyt @Trivo25?

**Comment by Trivo25** [comment]
If it helps, we could provide a branch that includes the fix until we can release a new version
